### ISSUE TITLE
Update docs to use the term "ZooKeeper" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#132]
# Description

"ZooKeeper" should always be written that way, we still have instances of "zookeeper" in the docus.

Occurrences of other usages should be replaced with the correct one. 

## Todo:

- [ ]  In the file `.github/vale/styles/Klaw/branding.yml`, add this Vale style:  `"(?i)zookeeper": ZooKeeper` 
    -  this will find the wrong spelling of ZooKeeper and mark them as error
- [ ]  run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number, for example:

<img width="756" alt="Screenshot 2023-10-05 at 09 34 48" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/a2a50638-df56-473e-bc9d-37315a1b351d">

- [ ]  update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by csengineer1990** [comment]
Hi @programmiri  mam can I work on the above issue?

**Comment by programmiri** [comment]
Hi! Yes, of course, I'll assign you :) Thank you!

**Comment by csengineer1990** [comment]
Thank you mam @programmiri
